### ISSUE TITLE
Citations should be DOI or pubmed

### ISSUE THREAD

**Issue by udp** [ICO2S/synbiohub#104]

**Comment by cjmyers** [comment]
For pubmed IDs

http://www.ebi.ac.uk/ols/ontologies/obi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0001617

http://purl.obolibrary.org/obo/OBI_0001617

**Comment by cjmyers** [comment]
DOI

http://www.ebi.ac.uk/ols/ontologies/cheminf/properties?iri=http%3A%2F%2Fpurl.org%2Fontology%2Fbibo%2Fdoi

http://purl.org/ontology/bibo/doi

**Comment by cjmyers** [comment]
Not sure how to use these in the links.  Also, currently citations are dropped.

**Comment by cjmyers** [comment]
Changed annotation for PubMed Number and added rendering of citation to collection page.
