### ISSUE TITLE
Forgotten password link doesn't work

### ISSUE THREAD

**Issue by udp** [ICO2S/synbiohub#4]

**Comment by cjmyers** [comment]
Quick temporary hack:
1) Open a page that is referenced with hashcode.
2) Page allows user to change password.

In future, replace jump to page with email the link.

**Comment by cjmyers** [comment]
Ok, quick fix is in, but need the email part to make it secure.

**Comment by cjmyers** [comment]
What is the status of this one?  I've tried to reset but did not receive any email.

**Comment by cjmyers** [comment]
Hmm, finally showed up.  Very slow though.

**Comment by cjmyers** [comment]
Done
