### ISSUE TITLE
Label issues on viewing a component

### ISSUE THREAD

**Issue by goksel** [ICO2S/synbiohub#62]
1) Collections -> In Collections
2) Search links should be replaced with search buttons
3) The table should be split into multiple tables
4) Not display everything. Public and private labels should not be displayed for now or replaced with icons perhaps.
5) Remove namespaces when displaying on the part page
6) Having the Version link for a sequence is confusing. The same link is displayed twice using different labels
7) When clicking to an identifier link, this should take user directly to the detail page, not to the search results page

**Comment by cjmyers** [comment]
1) done
2) I tried this, but the buttons were pretty big and looked awkward, especially for collections, roles, etc.
3) What do you mean by this?  Can you provide an example?
4) These will likely all go away (or be moved to the mouse over) once the icons are clickable in the diagrams, and we can support FunctionalComponents/Modules in the diagrams.
5) What do you mean by this one, please provide an example?  Do you mean the prefixes?  I'm using this to make clear annotations that are not part of SBOL proper.
6) Which one?  I checked the Sequence page and there is only one link.  The link for the identifier is to find all objects with the same displayId while the link for the Version finds all objects with the same persistentIdentity.
7) The detail page is the one you are looking at. The reason it goes to search is it is used to find all objects with the same displayId with perhaps different URI prefixes or versions.

**Comment by cjmyers** [comment]
Note that 1 might cause line breaks on the label column.  Not sure how to avoid this.

**Comment by goksel** [comment]
2. Try this instead of the "search" text:
<img src="search.png" height="30px">
Here is a search button:
![search](https://cloud.githubusercontent.com/assets/55247/21895205/b9d9e6b8-d8d9-11e6-83f0-5ee0dadcb032.png)

3. The row starting with "Components" should be a separate table.
5. igem:Planning should be Planning. There can be a title tag populated as "igem:Planning"
<a href="http://parts.igem.org/Help:Part_Status_Box" title="igem: Planning">Planning</a>

This one is debatable. It is your choice.

6. Exmaple:
http://synbiohub.utah.edu/public/igem/BBa_K861345/1
Sequences	BBa_K861345_sequence Version 1

Links in  "BBa_K861345_sequence" and "Version" are the same

**Comment by cjmyers** [comment]
2. This icon does not look good when there are many items to search by (sent you screenshot).
3. I think this will get removed completely once the icons in the visBoL diagrams become clickable and show their features with mouse over.
5. See your point.  Will remove version link.

**Comment by cjmyers** [comment]
You can set the height of the icons to a smaller value but I am not sure if it would look nice! Alternatively, the text and the button can be in a row together, and the row can be expanded according to the height of the button. 

As a user, I would like the links on the lefthand side to do the search directly, rather than going to the detail pages for categories. Why do not we display the category descriptions, next to the links. I am not sure which one would be better. We can ask to a few people and choose maybe!

Goksel

**Comment by cjmyers** [comment]
5) Do not display URIs in annotations.  Display linkable tag to full URL, and last part of URI linkable to definition.

**Comment by cjmyers** [comment]
7. Change the hover over to describe what clicking does for now.

**Comment by cjmyers** [comment]
I think this one is done.  Goksel: please check.
