### ISSUE TITLE
Add additional glyphs for all iGEM part / feature types

### ISSUE THREAD

**Issue by cjmyers** [ICO2S/synbiohub#65]
Include new non-standard SBOL/iGEM inspired glyphs for every part/feature type.

**Comment by goksel** [comment]
Especially for operators. Perhaps, it is one of the first parts to start with.

**Comment by cjmyers** [comment]
HERE ARE THE ONES WE NEED GLYPHS FOR:
Chromosome
oriT
Plasmid
Plasmid Vector
Primer
Polypeptide Domain
mature_transcript_region
T7_RNA_Polymerase_Promoter (promoter?)
Tag

**Comment by cjmyers** [comment]
Should likely also have glyphs for these feature types:
Engineered Tag
non_covalent_binding_site
sequence_alteration
polyA_site
primer_binding_site
point mutation
start codon
stop codon
tag
conserved region
stem loop

**Comment by cjmyers** [comment]
Tag, oriT, polypeptide domain, mature_transcript_region, polyA_site, Text Glyph (polyA, point, start, stop), stem loop

**Comment by udp** [comment]
Examples

Tag
http://parts.igem.org/Part:BBa_J63008
![icon_tag](https://cloud.githubusercontent.com/assets/454895/22209469/81d6f064-e17e-11e6-88d9-bf850811cb2a.png)

oriT  
http://parts.igem.org/Part:BBa_J01003
![icon_conjugation](https://cloud.githubusercontent.com/assets/454895/22209477/85294334-e17e-11e6-95fc-c400f692c814.png)

polypeptide domain
http://parts.igem.org/Part:BBa_K112327
![icon_protein_domain](https://cloud.githubusercontent.com/assets/454895/22209483/892a0d38-e17e-11e6-9cf6-132972006b0e.png)

mature_transcript_region
http://parts.igem.org/Part:BBa_K152008
![icon_rna](https://cloud.githubusercontent.com/assets/454895/22209484/8d8a94b0-e17e-11e6-9686-06032530dd59.png) (rna icon)

polyA_site
http://parts.igem.org/wiki/index.php?title=Part:BBa_K678019

**Comment by udp** [comment]
Do we actually set an SO term for polyA?

**Comment by udp** [comment]
I can't match most of these because we currently only map SO terms in roles to glyphs.  Should we change this to map any URI?  Are all the igem types in the role field?

**Comment by goksel** [comment]
Yes, we can set an SO term for polyA. I believe it may already be in the list of mappings we came up with. There is document with all these mappings.

**Comment by cjmyers** [comment]
Tag, RNA, stem_loop, text_glyph (polyA)

**Comment by cjmyers** [comment]
Opened separate issues for these.
