### ISSUE TITLE
Should be able to display pages stuff even if references missing entities

### ISSUE THREAD

**Issue by udp** [ICO2S/synbiohub#81]

**Comment by cjmyers** [comment]
Can you provide more detail or an example?

**Comment by cjmyers** [comment]
There is a problem with the sbolstack-api.  In getSBOL.js, an error is thrown when a URI cannot be resolved.  This prevents incomplete documents from being viewed.

**Comment by cjmyers** [comment]
This is fixed.  It fetches missing objects using their URIs and allows incomplete documents.
