### ISSUE TITLE
Find better ontology terms for the submit optional properties

### ISSUE THREAD

**Issue by cjmyers** [ICO2S/synbiohub#92]

**Comment by udp** [comment]
Is this really priority?

**Comment by cjmyers** [comment]
Remove, chassis, purpose.  Find better terms for keywords and citations.

**Comment by cjmyers** [comment]
Removed chassis, purpose.

**Comment by udp** [comment]
For pubmed IDs

http://www.ebi.ac.uk/ols/ontologies/obi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0001617

http://purl.obolibrary.org/obo/OBI_0001617

**Comment by udp** [comment]
Keyword (possibly though I haven't heard of this ontology)

http://www.ebi.ac.uk/ols/ontologies/sio/terms?iri=http%3A%2F%2Fsemanticscience.org%2Fresource%2FSIO_000147

http://semanticscience.org/resource/SIO_000147

**Comment by udp** [comment]
DOI

http://www.ebi.ac.uk/ols/ontologies/cheminf/properties?iri=http%3A%2F%2Fpurl.org%2Fontology%2Fbibo%2Fdoi

http://purl.org/ontology/bibo/doi

**Comment by cjmyers** [comment]
Replaced with new issues.
