### ISSUE TITLE
Making submissions public for large submissions does not work

### ISSUE THREAD

**Issue by goksel** [ICO2S/synbiohub#93]
This is an easy fix. When making submissions public,  some data are logged and this process makes it very slow when dealing with large submissions.Eventually, the process cannot be completed.

**Comment by cjmyers** [comment]
There was a print in sbolstack-frontend upload of the entire file.  I've removed this.  Please see if this solves the problem for you.  If so, please close this.

**Comment by cjmyers** [comment]
Okay found another big debug in sboljs, and removed that too

**Comment by cjmyers** [comment]
The problem is in loadRDF from the repository for large files.  This is very inefficient.  Should be replaced with carefully crafted SPARQL queries to grab the SBOL document.

**Comment by cjmyers** [comment]
Duplicate
